### ISSUE TITLE
Hiding user name & password in .js

### ISSUE THREAD

**Issue by daveeel** [nickcolley/getting-started-todo#1]
The username and password of remote couchdb is plain text in the source. How to fix this security issue?

**Comment by NickColley** [comment]
You can prompt the user for their password.

CouchDB has basic HTTP auth built in: http://guide.couchdb.org/draft/security.html#authentication

For anything non-trivial you can give https://github.com/nolanlawson/pouchdb-authentication a try :)

**Comment by dave-lee-hk** [comment]
By prompting the user for their password, that assumes the user is already signed. What if the App is for anonymous users, say commenting or chat? Guess I need to set the target remote DB to be readable & writable by everyone but have some validation function to limit the format?

As a related aside, is there an example of elegant way to do user signup on remote couchdb via pouchdb?

**Comment by daveeel** [comment]
Thanks. The later seems to be what I need but pity it's no longer maintained.

**Comment by NickColley** [comment]
Thanks for the issue @dave-lee-hk :+1:
