### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by ceremcem** [nickcolley/getting-started-todo#3]
Not working for me, without throwing any errors. I type something, and press ENTER, expecting something to add and see in a list.

**Comment by nolanlawson** [comment]
Are you running a server with `python -m SimpleHTTPServer`?

**Comment by ceremcem** [comment]
Yes, I'm. (I don't get why python server is required though, shouldn't it work directly in browser?)

**Comment by ceremcem** [comment]
The [update-pouchdb](https://github.com/pouchdb/pouchdb/issues/5399#issuecomment-228548949) branch works as expected. Thank you.
