### ISSUE TITLE
app.js:163 Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Steviey** [nickcolley/getting-started-todo#7]
app.js:163 Uncaught TypeError: Cannot read property 'addEventListener' of null

I' can't get it synced to localhost too.

If something would have to work out off the box, then a TodoMVC.

Win7, CouchDB/PouchDB latest versions.

**Comment by NickColley** [comment]
Please reopen with an example that reproduces this, will close this for now 👍
