### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Steviey** [nickcolley/getting-started-todo#8]
Ad-Blocker like yMatrix (often seen in nerdy environments) will produce ERR_BLOCKED_BY_CLIENT in PouchDB and CouchDB (XHR even on localhost).

Would be nice to have this info in the getting started guide- to save some hours of investigations.

**Comment by NickColley** [comment]
This is interesting, if you'd like feel free to open a PR over at the main PouchDB repo

https://github.com/pouchdb/pouchdb/edit/master/docs/errors.md
